#Author: Michael Bonner 
#Date: 20190624 

server:
    port: 8080

openWeatherMapAPIKey: ef2caccba4bb72d2c7b2607a0b0ad50b

spring:
    application:
        name: whatsTheWeatherApp 
    resources:
        static-locations: file:/var/www/static,classpath:static

#ribbon:
#  ServerListRefreshInterval: 1000

#endpoints:
#  health:
#    sensitive: false
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true

